### PR TITLE
Moved to poseidon-hs

### PR DESCRIPTION
**Pull request by stschiff**
When merged, this would essentially remove this package. Everything has been moved to poseidon-hs. I have left a note in the README.

### CODE REVIEW

**Comment by stschiff** [comment]
This is connected to https://github.com/poseidon-framework/poseidon-hs/pull/265

**Comment by nevrome** [comment]
I mean... we don't have to delete everything here, right? We could do what we did in the past with deprecated repositories: Adjust the README to point to the new resource and then archive it. That makes it reasonably clear that it's deprecated without preventing anybody from forking.

**Comment by stschiff** [comment]
Yeah, I thought so, too, at first, but then was unsatisfied by the (outdated) redundancy. But yes, happy to amend this PR, perhaps you're right and that is the most natural thing to do.

**Comment by stschiff** [comment]
Done. Also included a deprecation warning to the README.

**Pull request closed without merging**
